### ISSUE TITLE
Add darthsteven to organisation members

### ISSUE THREAD

**Issue by darthsteven** [OxDUG/website#1]
@finnlewis If we're going to build a website, should we do it here and get everyone added to the OxDUG organisation on github?

**Comment by finnlewis** [comment]
Hi Steven, yes, here would be a good start I think. There was talk of Gitlab last night, but as far as I know the hosted Gitlab doesn't have free version for open source projects.

So I think it makes sense to start here.

**Comment by darthsteven** [comment]
Lovely, we should probably have a signup link for people somewhere, and we could just gather a nice long list of usernames to add to a team or something.

**Comment by darthsteven** [comment]
Thanks!
